from __future__ import annotations


REQUIRED_SHARED_INPUTS = [
    "capabilities.md",
    "context.md",
    "design-slice.md",
    "design-seed.md",
    "state.md",
    "history.md",
    "dependencies.md",
    "gates.md",
    "memory.md",
    "records/memory.jsonl",
    "debt.md",
    "records/debt.jsonl",
    "accounting.json",
    "accounting.md",
    "records/invocations.jsonl",
    "execution-board.md",
    "agent-assignments.md",
    "team-overrides.md",
    "dispatch/",
    "parallel-dispatch/",
    "role-reviews.md",
    "review-log.md",
    "conflicts.md",
    "assumptions.md",
    "decisions.md",
    "team-minutes.md",
    "feedback-synthesis.json",
    "feedback-synthesis.md",
    "issue-advisor.json",
    "issue-advisor.md",
    "records/adaptations.jsonl",
    "replan.json",
    "replan.md",
    "records/replans.jsonl",
    "replans/",
    "verify-fix.json",
    "verify-fix.md",
    "records/verify-fix.jsonl",
    "ci-feedback.json",
    "ci-feedback.md",
    "ci-runs/",
    "records/ci-feedback.jsonl",
    "integration-test-allowlist.json",
    "integration-test-allowlist.md",
    "integration-test-gate.json",
    "integration-test-gate.md",
    "integration-runs/",
    "records/integration-gate-runs.jsonl",
    "agent-results/",
    "agent-sync-ledger.md",
    "agent-result-schema.md",
    "schemas/agent-result.schema.json",
    "records/agent-result-validation.jsonl",
    "links.md",
    "workflow-contract.md",
    "runtime-contract.md",
]


GENERATED_SHARED_ARTIFACTS = [
    "stories.md",
    "story-*.md",
    "dag.json",
    "dag.md",
    "dag-validation.md",
    "execution-path.json",
    "execution-path.md",
    "implementation-plan.md",
    "release-plan.md",
    "team-dispatch.md",
    "dispatch/*.md",
    "parallel-dispatch.json",
    "parallel-dispatch.md",
    "parallel-dispatch/*",
    "worktrees/manifest.json",
    "worktrees.md",
    "merge-gate.json",
    "merge-gate.md",
    "merge-apply.json",
    "merge-apply.md",
]


REQUIRED_SHARED_OUTPUTS = [
    "code/tests/docs in assigned scope",
    "records/memory.jsonl updates",
    "memory.md summaries",
    "records/debt.jsonl updates",
    "debt.md summaries",
    "records/invocations.jsonl updates",
    "accounting.md summaries",
    "role-reviews.md verdicts",
    "conflicts.md entries",
    "assumptions.md updates",
    "review-log.md evidence",
    "feedback-synthesis.json recommendations",
    "feedback-synthesis.md recommendations",
    "issue-advisor.json recovery advice",
    "issue-advisor.md recovery advice",
    "records/adaptations.jsonl updates",
    "replan.json proposals/applications",
    "replan.md proposals/applications",
    "records/replans.jsonl updates",
    "verify-fix.json findings",
    "verify-fix.md findings",
    "records/verify-fix.jsonl updates",
    "ci-feedback.json findings",
    "ci-feedback.md findings",
    "records/ci-feedback.jsonl updates",
    "merge-gate.json readiness evidence",
    "merge-gate.md readiness evidence",
    "merge-apply.json apply evidence",
    "merge-apply.md apply evidence",
    "integration-test-gate.json evidence",
    "integration-test-gate.md evidence",
    "integration-runs/ execution records",
    "records/integration-gate-runs.jsonl updates",
    "records/agent-result-validation.jsonl updates",
    "agent-results/ envelopes",
    "agent-sync-ledger.md updates",
    "parallel-dispatch/ packets",
    "dispatch/ packets",
    "worktrees/manifest.json updates",
    "execution-board.md notes",
    "team-minutes.md updates",
]


def format_shared_items(items: list[str]) -> str:
    return ", ".join(items)
